### ISSUE TITLE
multiple players wont work 

### ISSUE THREAD

**Issue by sydney1419** [lax1dude/crashreport-viewer#2]
Game Crashed! I have fallen and I can't get up! please help i dont know how to code.

**Comment by lax1dude** [comment]
I don't understand the mental gymnastics how people come to the conclusion that the text "Game Crashed! I have fallen and I can't get up!" is the only relevant part of the crash report that they need to post to get help. Please paste the full crash report next time and also I am no longer updating this project so whatever problem you are having is something you're just gonna have to live with :/

**Comment by lax1dude** [comment]
please don't reopen this issue or any new ones, this is not the place
